trigger:
  branches:
    include:
      - master
      - develop

  paths:
    include:
      - AuditLog/
      - AuditLog.ConsoleClient/
      - AuditLog.DAL/
      - AuditLog.DAL.Test/
      - AuditLog.Domain/
      - AuditLog.Test/
      - azure-pipelines.yaml


variables:
  buildConfiguration: 'Release'
  projects: |
    AuditLog/AuditLog.csproj
    AuditLog.DAL/AuditLog.DAL.csproj
    AuditLog.Domain/AuditLog.Domain.csproj
    AuditLog.ConsoleClient/AuditLog.ConsoleClient.csproj
  testProjects: |
    AuditLog.Test/AuditLog.Test.csproj
    AuditLog.DAL.Test/AuditLog.DAL.Test.csproj
  projectKey: WimG:AudiLog
  projectName: Wim de Groot AuditLog

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: SonarQubePrepare@4
            condition: eq(variables['build.sourcebranch'], 'refs/heads/master')
            inputs:
              SonarQube: 'SonarQube Service Connection'
              scannerMode: 'MSBuild'
              projectKey: $(projectKey)
              projectName: $(projectName)

          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              projects: $(projects)
              arguments: '--configuration $(BuildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
              command: test
              projects: $(testProjects)
              arguments: '--configuration $(BuildConfiguration) --collect:"Code Coverage"'

          - task: SonarQubeAnalyze@4
            condition: eq(variables['build.sourcebranch'], 'refs/heads/master')
          - task: SonarQubePublish@4
            condition: eq(variables['build.sourcebranch'], 'refs/heads/master')
            inputs:
              pollingTimeoutSec: '300'
          - task: sonar-buildbreaker@8
            condition: eq(variables['build.sourcebranch'], 'refs/heads/master')
            inputs:
              SonarQube: 'SonarQube Service Connection'

  - stage: Release
    displayName: Release
    jobs: 
      - job: Release
        displayName: Release
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'dotnet publish'
            inputs:
              command: publish
              projects: AuditLog.ConsoleClient/AuditLog.ConsoleClient.csproj
              patchVersion: $(Build.BuildId)

          - task: Docker@2
            displayName: 'docker build and publish'
            inputs:
              containerRegistry: 'wimdegroot'
              repository: 'audit-log'
              tags: $(Build.BuildId)
              buildContext: 'AuditLog.ConsoleClient/AuditLog.ConsoleClient/'
              Dockerfile: 'AuditLog.ConsoleClient/AuditLog.ConsoleClient/Dockerfile'

          